version: "3.5"
services:
  mong_golang:
    image: newone
    restart: always
    environment:
        - PORT=8080
        - DB_NAME="golang"
        - DB_HOST="127.0.0.1"
    ports:
        - '8080:8080'